# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CrashReportUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CrashReportDialog(object):
    def setupUi(self, CrashReportDialog):
        CrashReportDialog.setObjectName("CrashReportDialog")
        CrashReportDialog.resize(240, 137)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CrashReportDialog.sizePolicy().hasHeightForWidth())
        CrashReportDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(CrashReportDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(CrashReportDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(-1, 9, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(CrashReportDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.le_pivkey = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_pivkey.sizePolicy().hasHeightForWidth())
        self.le_pivkey.setSizePolicy(sizePolicy)
        self.le_pivkey.setObjectName("le_pivkey")
        self.gridLayout.addWidget(self.le_pivkey, 1, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.tb_save = QtWidgets.QToolButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_save.sizePolicy().hasHeightForWidth())
        self.tb_save.setSizePolicy(sizePolicy)
        self.tb_save.setMinimumSize(QtCore.QSize(0, 0))
        self.tb_save.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tb_save.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tb_save.setObjectName("tb_save")
        self.gridLayout.addWidget(self.tb_save, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(CrashReportDialog)
        QtCore.QMetaObject.connectSlotsByName(CrashReportDialog)

    def retranslateUi(self, CrashReportDialog):
        _translate = QtCore.QCoreApplication.translate
        CrashReportDialog.setWindowTitle(_translate("CrashReportDialog", "崩溃报告"))
        self.label.setText(_translate("CrashReportDialog", "使用此功能会向开发者提供崩溃报告，在下方输入开发者提供的身份识别码（PIV_KEY）。"))
        self.label_2.setText(_translate("CrashReportDialog", "PIV_KEY："))
        self.tb_save.setText(_translate("CrashReportDialog", "认证"))
