# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowLogDialog(object):
    def setupUi(self, ShowLogDialog):
        ShowLogDialog.setObjectName("ShowLogDialog")
        ShowLogDialog.resize(450, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ShowLogDialog.sizePolicy().hasHeightForWidth())
        ShowLogDialog.setSizePolicy(sizePolicy)
        ShowLogDialog.setStyleSheet("background-color: rgb(30, 35, 61)")
        self.verticalLayout = QtWidgets.QVBoxLayout(ShowLogDialog)
        self.verticalLayout.setContentsMargins(0, -1, 0, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(ShowLogDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.te_showlog = QtWidgets.QTextEdit(self.widget)
        self.te_showlog.setMinimumSize(QtCore.QSize(0, 0))
        self.te_showlog.setStyleSheet("background-color: rgb(30, 35, 61);\n"
"color: rgb(233, 222, 216);")
        self.te_showlog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.te_showlog.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.te_showlog.setReadOnly(True)
        self.te_showlog.setObjectName("te_showlog")
        self.verticalLayout_2.addWidget(self.te_showlog)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(ShowLogDialog)
        QtCore.QMetaObject.connectSlotsByName(ShowLogDialog)

    def retranslateUi(self, ShowLogDialog):
        _translate = QtCore.QCoreApplication.translate
        ShowLogDialog.setWindowTitle(_translate("ShowLogDialog", "日志"))
        self.te_showlog.setHtml(_translate("ShowLogDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
